chore: downgrade sentry/sveltekit back to 8.x
See what it does in prod (maybe it peerdepends on vite 6 and i read the
migration guide too quickly):

Starting churros app...
Listening on http://0.0.0.0:3000
node:internal/modules/cjs/loader:1225
  const err = new Error(message);
              ^

Error: Cannot find module 'vite'
Require stack:
- /app/node_modules/@sentry/sveltekit/build/cjs/vite/sourceMaps.js
- /app/node_modules/@sentry/sveltekit/build/cjs/vite/sentryVitePlugins.js
- /app/node_modules/@sentry/sveltekit/build/cjs/index.server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Module.<anonymous> (/app/node_modules/@sentry/sveltekit/build/cjs/vite/sourceMaps.js:9:14)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@sentry/sveltekit/build/cjs/vite/sourceMaps.js',
    '/app/node_modules/@sentry/sveltekit/build/cjs/vite/sentryVitePlugins.js',
    '/app/node_modules/@sentry/sveltekit/build/cjs/index.server.js'
  ]
}

Node.js v20.18.2
stream closed EOF for churros-prod/churros-app-77798ccfd6-58ds8 (app)

------------------------------------------------------------------------------------------------------------------------

 ██████╗███████╗███╗   ██╗████████╗██████╗  █████╗ ██╗   ██╗███████╗██████╗ ███████╗███████╗     █████╗ ██████╗ ██████╗
██╔════╝██╔════╝████╗  ██║╚══██╔══╝██╔══██╗██╔══██╗██║   ██║██╔════╝██╔══██╗██╔════╝██╔════╝    ██╔══██╗██╔══██╗██╔══██╗
██║     █████╗  ██╔██╗ ██║   ██║   ██████╔╝███████║██║   ██║█████╗  ██████╔╝███████╗█████╗      ███████║██████╔╝██████╔╝
██║     ██╔══╝  ██║╚██╗██║   ██║   ██╔══██╗██╔══██║╚██╗ ██╔╝██╔══╝  ██╔══██╗╚════██║██╔══╝      ██╔══██║██╔═══╝ ██╔═══╝
╚██████╗███████╗██║ ╚████║   ██║   ██║  ██║██║  ██║ ╚████╔╝ ███████╗██║  ██║███████║███████╗    ██║  ██║██║     ██║
 ╚═════╝╚══════╝╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝    ╚═╝  ╚═╝╚═╝     ╚═╝

------------------------------------------------------------------------------------------------------------------------

Starting churros app...
Listening on http://0.0.0.0:3000
node:internal/modules/cjs/loader:1225
  const err = new Error(message);
              ^

Error: Cannot find module 'vite'
Require stack:
- /app/node_modules/@sentry/sveltekit/build/cjs/vite/sourceMaps.js
- /app/node_modules/@sentry/sveltekit/build/cjs/vite/sentryVitePlugins.js
- /app/node_modules/@sentry/sveltekit/build/cjs/index.server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Module.<anonymous> (/app/node_modules/@sentry/sveltekit/build/cjs/vite/sourceMaps.js:9:14)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@sentry/sveltekit/build/cjs/vite/sourceMaps.js',
    '/app/node_modules/@sentry/sveltekit/build/cjs/vite/sentryVitePlugins.js',
    '/app/node_modules/@sentry/sveltekit/build/cjs/index.server.js'
  ]
}

Node.js v20.18.2
stream closed EOF for churros-prod/churros-app-77798ccfd6-58ds8 (app)